/*
 * ReceiveBook.java
 *
 * Created on August 19, 2012, 11:12 PM
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author  Administrator
 */
public class ReceiveBook extends javax.swing.JFrame {
    
    /** Creates new form ReceiveBook */
    public ReceiveBook() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtMemberID = new javax.swing.JTextField();
        CmdMemberDetails = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtMemberName = new javax.swing.JTextField();
        CmdReset = new javax.swing.JButton();
        CmdReceiveBook = new javax.swing.JButton();
        CmdClose = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LblBookID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lateFeesField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aksharbag : Receive Book");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Aksharbag  - Receive Book");

        jLabel3.setText("Member ID :");

        TxtMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMemberIDActionPerformed(evt);
            }
        });

        CmdMemberDetails.setText("Details");
        CmdMemberDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdMemberDetailsActionPerformed(evt);
            }
        });

        jLabel2.setText("Name :");

        TxtMemberName.setEditable(false);
        TxtMemberName.setText("jTextField1");

        CmdReset.setText("Reset");
        CmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdResetActionPerformed(evt);
            }
        });

        CmdReceiveBook.setText("Receive Book");
        CmdReceiveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdReceiveBookActionPerformed(evt);
            }
        });

        CmdClose.setText("Close");
        CmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdCloseActionPerformed(evt);
            }
        });

        jLabel4.setText("Book :");

        LblBookID.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        LblBookID.setForeground(java.awt.Color.lightGray);

        jLabel5.setText("Late Fees :");

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CmdReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmdReceiveBook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmdClose))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)
                                .addComponent(TxtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(18, 38, Short.MAX_VALUE)
                                .addComponent(LblBookID)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CmdMemberDetails)
                                        .addComponent(TxtMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(lateFeesField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmdMemberDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(LblBookID))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lateFeesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdReset)
                    .addComponent(CmdReceiveBook)
                    .addComponent(CmdClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmdMemberDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdMemberDetailsActionPerformed
        //get member deatils
        try {
            //get database connection details
            MainClass mc=new MainClass();
            
            //open connection
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            String str="";
            str="select * from lib_member_master where mem_id =? ";
            PreparedStatement pst=connection.prepareStatement(str);
            pst.setString(1, TxtMemberID.getText());
            
            ResultSet rs;
            rs=pst.executeQuery();
            if (rs.next()) {
                TxtMemberName.setText(rs.getString("mem_name"));
                
                //get mem status
                str="select * from lib_transaction, lib_book_master where book_id=trn_book_id and trn_mem_id =? and (trn_receive_dt is null  or trn_receive_dt='')";
                PreparedStatement pst1=connection.prepareStatement(str);
                pst1.setString(1, TxtMemberID.getText());
                
                ResultSet rs1;
                rs1=pst1.executeQuery();
                DefaultListModel<String> model;
                model = new DefaultListModel<String>();
                CmdReceiveBook.setEnabled(false);
                    //LblBookID.setText("");
                while (rs1.next()) {
                    CmdReceiveBook.setEnabled(true);
                   // LblBookID.setText(rs1.getString("book_id"));
                    //TxtBookDetails.setText("Available Book : " + rs1.getString("book_title"));
                    //jList1.addO
                    model.addElement(rs1.getString("book_id") + "~" + rs1.getString("book_title"));
                    
                    CmdReceiveBook.setEnabled(true);
                   // LblBookID.setText(rs1.getString("book_id"));

                } 
                jList1.setModel(model);
            } else {
                JOptionPane.showMessageDialog(null,"Invalid member id.");
                TxtMemberID.setText("");
                TxtMemberName.setText("");
               // TxtBookDetails.setText("");
                CmdReceiveBook.setEnabled(false);
               // LblBookID.setText("");
                return;
            }
            
            
        } catch (Exception e) {
            System.err.println(e);
            System.exit(1);
        }
    }//GEN-LAST:event_CmdMemberDetailsActionPerformed

    private void CmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdResetActionPerformed
        ClearText();
    }//GEN-LAST:event_CmdResetActionPerformed

    private void CmdReceiveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdReceiveBookActionPerformed
        //issue book
        try {
            
            
            if (TxtMemberID.getText().trim().length()==0 ) {
                JOptionPane.showMessageDialog(null,"Enter member id.");
                return;
            }
            
            ListModel model = jList1.getModel();
            List<Integer> selectedBookIds  = new ArrayList<Integer>();
if(jList1.getSelectedIndices().length == 0){
                 JOptionPane.showMessageDialog(null,"No books selected.");
                return;
 }else{
for(int index : jList1.getSelectedIndices()) { 
           String book = (String)model.getElementAt(index);
              
    
                selectedBookIds.add(Integer.parseInt(book.split("~")[0]));
}
}
            //Integer bookId = jList1
          
          MainClass mc=new MainClass();
            Connection connection;
            connection=DriverManager.getConnection(mc.StrUrl,mc.StrUid,mc.StrPwd);
            for(Integer bookId : selectedBookIds){
                String sql = "update  lib_transaction set trn_receive_dt = curdate() where trn_mem_id= " + TxtMemberID.getText() + " and trn_receive_dt is null and trn_book_id=" + bookId;
                PreparedStatement pst=connection.prepareStatement(sql);
                pst.executeUpdate(sql);
                if (lateFeesField.getText().trim().length()!=0 ) {
                    String sql2 = "update  lib_transaction set late_fees = " + lateFeesField.getText() + " where trn_mem_id= " + TxtMemberID.getText() + "  and trn_book_id=" + bookId;
                    PreparedStatement pst2=connection.prepareStatement(sql2);
                    pst2.executeUpdate(sql2);
                }
                sql = "update  lib_book_master set book_status='Available' where book_id=" + bookId;
                pst=connection.prepareStatement(sql);
                    pst.executeUpdate(sql);
            }
           int index = jList1.getSelectedIndices().length - 1;

        while (jList1.getSelectedIndices().length != 0) {
            ((DefaultListModel) jList1.getModel()).removeElementAt(jList1.getSelectedIndices()[index--]);
        }
            JOptionPane.showMessageDialog(null,"Book Received");
           //s ClearText();
        } catch (Exception e) {
            System.err.println(e);
            System.exit(1);
        }
}//GEN-LAST:event_CmdReceiveBookActionPerformed
    
    private void ClearText()
    {
        TxtMemberID.setText("");
        TxtMemberName.setText("");
       // TxtBookDetails.setText("");
        LblBookID.setText("");

        CmdReceiveBook.setEnabled(false);

    }
    private void CmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_CmdCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               ClearText();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void TxtMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMemberIDActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiveBook().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmdClose;
    private javax.swing.JButton CmdMemberDetails;
    private javax.swing.JButton CmdReceiveBook;
    private javax.swing.JButton CmdReset;
    private javax.swing.JLabel LblBookID;
    private javax.swing.JTextField TxtMemberID;
    private javax.swing.JTextField TxtMemberName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lateFeesField;
    // End of variables declaration//GEN-END:variables
    
}
